### ISSUE TITLE
Swindler

### ISSUE THREAD

**Issue by Butonix** [thetruefuss/thetruefuss.github.io#1]
SwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindlerSwindler

**Comment by thetruefuss** [comment]
Sergey, it is you who have deceived several times. You ask for a project but do not like to pay. You did it so many times that you asked for the source code but did not send the payment. You don't even reply to my emails after that. That's exactly what you did two months ago. You promised to send the payment but you took the source code & went away. You lie. I always send you so many emails explaining my situation to you but you choose to stay quite & insensitive.

You should look at the project timeline. I worked on it for almost 8 months. Working Django website then Django API + ReactJS app then code migration to NextJS app. I had to copy the exact design as on the original web app & exact functionality. I implemented each & every feature to the project that they were offering at the time. I had to put in a lot of work to get the project completed. You paid a lot less. Plus you lied & deceived me several times.

Mentioning the word "Swindler" 59 times does not change the fact that it's you who deceives.

**Comment by Butonix** [comment]
You asked me 100 times for extra money!We agreed on 500$ you pulled me out of 1200$!  It doesn't matter! I filed a complaint against you in the international court of justice for fraud! All data and correspondence with you I gave them! All the best! Liar, fraud!

**Comment by thetruefuss** [comment]
You don't need to exaggerate. What more do I say when you are already aware of the facts? The stakes went up for a reason. You paid for what you asked for.  The initial project requirements were completely updated later. You kept asking to upgrade the project, add new features, make changes a lot etc. & you got to pay for it. You paid a lot less than it's actual worth. Look closely at the project timeline & it will help you change your perspective. Plus, you are already aware of everything. Good luck.

Regards
